# Generated by Django 3.0.6 on 2020-05-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='yahoo_league_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
