# Generated by Django 3.0.6 on 2020-05-30 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0002_managerprofile_yahoo_league_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league_name',
        ),
        migrations.AddField(
            model_name='team',
            name='yahoo_team_logo_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
