# Generated by Django 3.0.6 on 2020-06-09 21:22

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('frontoffice', '0003_auto_20200530_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='yahoo_game_code',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='yahoo_game_id',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='yahoo_season_year',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
