# Generated by Django 3.0.6 on 2020-06-10 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0003_auto_20200530_0136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='team',
        ),
        migrations.CreateModel(
            name='RosterEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='starting', max_length=200)),
                ('at_position', models.CharField(default='pitcher', max_length=200)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontoffice.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='frontoffice.Team')),
            ],
        ),
    ]
