# Generated by Django 3.0.6 on 2020-05-21 21:34

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('frontoffice', '0003_auto_20200521_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='YahooAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yahoo_email', models.CharField(max_length=200)),
                ('yahoo_url', models.CharField(max_length=200)),
                ('yahoo_token', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontoffice.PlayerUser')),
            ],
        ),
    ]
