# Generated by Django 3.0.6 on 2020-06-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0005_auto_20200610_0148'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='headshot_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
