# Generated by Django 3.0.6 on 2020-05-24 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0006_auto_20200524_0110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='team_name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='team',
            name='save_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 7, 7, 58, 133667), verbose_name='date saved'),
        ),
    ]
