# Generated by Django 3.0.6 on 2020-06-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0006_player_headshot_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='primary_position',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
