# Generated by Django 3.0.6 on 2020-05-24 07:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0007_auto_20200524_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='save_date',
        ),
        migrations.AddField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='date created'),
            preserve_default=False,
        ),
    ]
