# Generated by Django 3.0.6 on 2020-06-10 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0007_player_primary_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rosterentry',
            name='status',
        ),
        migrations.AlterField(
            model_name='rosterentry',
            name='at_position',
            field=models.CharField(default='P', max_length=200),
        ),
    ]
