# Generated by Django 3.0.6 on 2020-05-26 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0008_auto_20200524_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamrecord',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontoffice.Team'),
        ),
    ]
