# Generated by Django 3.0.6 on 2020-06-11 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0008_auto_20200610_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='teams_in_league',
            field=models.ManyToManyField(to='frontoffice.Team'),
        ),
    ]
