# Generated by Django 3.0.6 on 2020-06-11 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0009_managerprofile_teams_in_league'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='disply_position',
            new_name='display_position',
        ),
        migrations.AlterField(
            model_name='rosterentry',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='roster_entries', to='frontoffice.Team'),
        ),
    ]
