# Generated by Django 3.0.6 on 2020-06-12 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0010_auto_20200611_2308'),
        ('frontoffice', '0004_auto_20200609_2122'),
    ]

    operations = [
    ]
