# Generated by Django 3.0.6 on 2020-06-12 22:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0011_merge_20200612_0631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlayerUser',
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='yahoo_league_last_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='league last updated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='roster_last_updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='roster last updated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='teams_in_league',
            field=models.ManyToManyField(related_name='manger_profiles', to='frontoffice.Team'),
        ),
    ]
