# Generated by Django 3.0.6 on 2020-06-15 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0012_auto_20200612_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='estimated_season_points',
            field=models.FloatField(null=True),
        ),
    ]
