# Generated by Django 3.0.6 on 2020-06-24 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0016_auto_20200616_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='active_mlb_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rosterentry',
            name='at_position',
            field=models.CharField(default='P', max_length=10),
        ),
    ]
