# Generated by Django 3.0.6 on 2020-06-24 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0017_auto_20200623_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('yahoo_id', models.CharField(max_length=200, null=True)),
                ('yahoo_key', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('season_year', models.CharField(max_length=200, null=True)),
                ('game_code', models.CharField(max_length=200, null=True)),
                ('game_id', models.CharField(max_length=200, null=True)),
                ('league_last_updated_at', models.DateTimeField(auto_now_add=True, verbose_name='league last updated')),
            ],
        ),
        migrations.AddField(
            model_name='managerprofile',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontoffice.League'),
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontoffice.League'),
        ),
    ]
