# Generated by Django 3.0.6 on 2020-06-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0018_auto_20200625_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='active_mlb_player',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
