# Generated by Django 3.0.6 on 2020-06-24 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0018_auto_20200623_2009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='league_last_updated_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='managerprofile',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manager_profile', to='frontoffice.League'),
        ),
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams_in_league', to='frontoffice.League'),
        ),
    ]
