# Generated by Django 3.0.6 on 2020-06-24 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0019_auto_20200624_1233'),
        ('frontoffice', '0017_auto_20200624_1048'),
    ]

    operations = [
    ]
