# Generated by Django 3.0.6 on 2020-06-24 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0020_merge_20200624_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='roster_slots_raw',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
