# Generated by Django 3.0.6 on 2020-06-25 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0019_auto_20200625_0533'),
        ('frontoffice', '0022_matchup'),
    ]

    operations = [
    ]
