# Generated by Django 3.0.6 on 2020-06-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0025_auto_20200625_1700'),
        ('frontoffice', '0024_auto_20200626_0723'),
    ]

    operations = [
    ]
