# Generated by Django 3.0.6 on 2020-07-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0026_merge_20200627_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatedplayerrecord',
            name='fangraphs_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='estimatedplayerrecord',
            name='singles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='fangraphs_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='singles',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='active_mlb_player',
            field=models.BooleanField(default=False),
        ),
    ]
