# Generated by Django 3.0.6 on 2020-07-02 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0032_auto_20200702_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatedplayerrecord',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontoffice.Player'),
        ),
        migrations.AlterField(
            model_name='playerrecord',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontoffice.Player'),
        ),
    ]
