# Generated by Django 3.0.6 on 2020-07-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0034_statcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='managerprofile',
            name='auto_manager',
            field=models.BooleanField(default=False),
        ),
    ]
