# Generated by Django 3.0.6 on 2020-07-03 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0035_managerprofile_auto_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managerprofile',
            name='auto_manager',
        ),
        migrations.AddField(
            model_name='team',
            name='auto_manager',
            field=models.BooleanField(default=False),
        ),
    ]
