# Generated by Django 3.0.6 on 2020-07-03 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0037_remove_team_auto_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='auto_manager',
            field=models.BooleanField(default=False),
        ),
    ]
