# Generated by Django 3.0.6 on 2020-07-06 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0038_team_auto_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerProjections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField(default=2020)),
                ('game_week', models.IntegerField(default=1)),
                ('fangraphs_id', models.IntegerField(default=0)),
                ('hits', models.IntegerField(default=0)),
                ('atbats', models.IntegerField(default=0)),
                ('singles', models.IntegerField(default=0)),
                ('doubles', models.IntegerField(default=0)),
                ('triples', models.IntegerField(default=0)),
                ('homeruns', models.IntegerField(default=0)),
                ('walks', models.IntegerField(default=0)),
                ('hbps', models.IntegerField(default=0)),
                ('stolen_bases', models.IntegerField(default=0)),
                ('caught_stealings', models.IntegerField(default=0)),
                ('innings_pitched', models.FloatField(default=0)),
                ('strikeouts', models.IntegerField(default=0)),
                ('hits_pitcher', models.IntegerField(default=0)),
                ('walks_pitcher', models.IntegerField(default=0)),
                ('hbps_pitcher', models.IntegerField(default=0)),
                ('homeruns_pitcher', models.IntegerField(default=0)),
                ('saves', models.IntegerField(default=0)),
                ('holds', models.IntegerField(default=0)),
                ('player', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontoffice.Player')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
