# Generated by Django 3.0.6 on 2020-07-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0041_auto_20200707_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='scoring_type',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
