# Generated by Django 3.0.6 on 2020-07-08 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0042_league_scoring_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yahooaccount',
            name='user',
        ),
        migrations.RemoveField(
            model_name='league',
            name='game_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='mlb_team',
        ),
        migrations.RemoveField(
            model_name='player',
            name='position',
        ),
        migrations.RemoveField(
            model_name='team',
            name='scoring_criteria',
        ),
        migrations.DeleteModel(
            name='EstimatedPlayerRecord',
        ),
        migrations.DeleteModel(
            name='ScoringCriteria',
        ),
        migrations.DeleteModel(
            name='YahooAccount',
        ),
    ]
