# Generated by Django 3.0.6 on 2020-07-09 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0043_auto_20200708_1632'),
        ('frontoffice', '0041_auto_20200708_0531'),
    ]

    operations = [
    ]
