# Generated by Django 3.0.6 on 2020-07-10 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0044_merge_20200708_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='is_bye',
            field=models.BooleanField(default=False),
        ),
    ]
