# Generated by Django 3.0.6 on 2020-07-10 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0046_gameweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameweek',
            name='leauge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameweek', to='frontoffice.League'),
        ),
        migrations.AddField(
            model_name='gameweek',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gameweek', to='frontoffice.Team'),
        ),
    ]
