# Generated by Django 3.0.6 on 2020-07-11 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0047_auto_20200710_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameweek',
            old_name='leauge',
            new_name='league',
        ),
        migrations.RemoveField(
            model_name='gameweek',
            name='team',
        ),
        migrations.AddField(
            model_name='gameweek',
            name='display_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
