# Generated by Django 3.0.6 on 2020-07-11 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0048_auto_20200710_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameweek',
            name='league',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_weeks', to='frontoffice.League'),
        ),
    ]
