# Generated by Django 3.0.6 on 2020-07-11 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0049_auto_20200710_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gameweek',
            old_name='game_week_end',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='gameweek',
            old_name='game_week_start',
            new_name='start',
        ),
    ]
