# Generated by Django 3.0.6 on 2020-07-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0050_auto_20200710_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameweek',
            name='end',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='gameweek',
            name='start',
            field=models.DateField(),
        ),
    ]
