# Generated by Django 3.0.6 on 2020-07-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0051_auto_20200712_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerprojections',
            name='rbis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerprojections',
            name='runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='rbis',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='runs',
            field=models.IntegerField(default=0),
        ),
    ]
