# Generated by Django 3.0.6 on 2020-07-18 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0052_auto_20200717_1631'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerProjections',
            new_name='PlayerProjection',
        ),
    ]
