# Generated by Django 3.0.6 on 2020-07-23 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0053_auto_20200718_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='display_position',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
