# Generated by Django 3.0.6 on 2020-08-02 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0055_auto_20200725_0929'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRotoProjectedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='playerprojection',
            name='earned_runs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerrecord',
            name='earned_runs',
            field=models.IntegerField(default=0),
        ),
    ]
